Product Feature Implementation
03mayank/shopping_app pull request #4
Opened 2022-09-05 14:22 UTC by 03mayank

Implemented Product feature, now admin user can list, edit and delete products and a user can see listed products.
![Screenshot from 2022-09-05 19-49-06](https://user-images.githubusercontent.com/110469010/188470228-1fb0e68d-42f2-41bb-961f-a80d28adb8f5.png)
![Screenshot from 2022-09-05 19-49-13](https://user-images.githubusercontent.com/110469010/188470233-03d842b4-2e3c-41cc-99e2-839a18a0a0c7.png)
![Screenshot from 2022-09-05 19-49-21](https://user-images.githubusercontent.com/110469010/188470237-19a67a41-6e67-4043-abea-9c809cba5e8b.png)
![Screenshot from 2022-09-05 19-49-35](https://user-images.githubusercontent.com/110469010/188470238-349cb7a4-840f-4ffd-bd06-b4af05de87b4.png)
![Screenshot from 2022-09-05 19-50-23](https://user-images.githubusercontent.com/110469010/188470242-36f36ed4-674c-4cf2-a89f-09c74340b68b.png)
ted product features. Now an Admin user can list products, adit and update them and a user can see the listed products.

2022-09-06 14:08 UTC, 03mayank commented
![Screenshot from 2022-09-06 19-36-18](https://user-images.githubusercontent.com/110469010/188656517-c3f4d698-e08c-4a27-95b8-f78a48ee4066.png)
![Screenshot from 2022-09-06 19-36-40](https://user-images.githubusercontent.com/110469010/188656535-4c351783-06dc-4793-bb47-43251ca03c49.png)

2022-09-06 14:23 UTC, 03mayank commented
Now Admin can upload images of the product, he is listing, and the user can see those images alongside product details.

2022-09-07 04:38 UTC, Nimish20 requested changes
@03mayank, I've left minor comments below. please address the comments.

2022-09-07 04:38 UTC, Nimish20 commented on app/views/products/index.html.erb
> +  <% Product.all.each do |product| %>
Use `@products` set in product controllers index action.

2022-09-07 04:38 UTC, Nimish20 commented on app/views/products/_form.html.erb
> +    <%= form.select :category_name, options_for_select(Category.all.pluck(:category_name)),
Try to avoid writing queries in view, set categories or category_names from the controller.

2022-09-07 04:38 UTC, Nimish20 commented on app/views/welcome/index.html.erb
> +    <% Product.all.each do |product| %>
Set products from the controller.

2022-09-07 04:38 UTC, Nimish20 commented on app/controllers/products_controller.rb
> +
Add end of the file correctly.

2022-09-07 10:25 UTC, 03mayank commented
Now admin user can upload multiple images of a product and the user can see all those images of a product.
![Screenshot from 2022-09-07 15-52-47](https://user-images.githubusercontent.com/110469010/188855622-01138361-4d33-49c2-833c-7e4d6ca88c87.png)
![Screenshot from 2022-09-07 15-52-57](https://user-images.githubusercontent.com/110469010/188855625-322d2ee5-4b7c-4f37-9e2c-52e98aaacc64.png)
![Screenshot from 2022-09-07 15-52-59](https://user-images.githubusercontent.com/110469010/188855631-345d2e4f-f06b-4926-9b09-5786b27e0116.png)
![Screenshot from 2022-09-07 15-52-35](https://user-images.githubusercontent.com/110469010/188855602-663ed28e-6797-464b-8706-465eaf1c8f64.png)
![Screenshot from 2022-09-07 15-52-39](https://user-images.githubusercontent.com/110469010/188855612-e946c454-950d-4132-a050-ae7b226a1158.png)

2022-09-13 06:41 UTC, Nimish20 approved these changes

2022-09-13 06:41 UTC, merged